# Generated by Django 3.2.4 on 2021-06-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_conact_date_contact_contact_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='usr_id',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
